### For deploying latest revision to Dev Server

      - name: Whitelisting IP
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
          aws-region: 'us-east-1'
          aws-security-group-id: ${{ secrets.DEV_AWS_SECURITY_GROUP_ID }}
          port: '22'
          command_timeout: 200m
          description: 'Github Action - BE'

      - name: Deploying
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          port: '22'
          command_timeout: 200m
          script: |
            kubectl get node